### ISSUE TITLE
Httpx issue 

### ISSUE THREAD

**Issue by zodmagus** [TaurusOmar/SubEnumX#2]
[INF] Enumerating subdomains for gomaps.com
Usage: httpx [OPTIONS] URL

Error: No such option: -l

**Comment by xf0mar** [comment]
cmd := exec.Command("httpx", "-l", subdomainsOutput, "-title", "-tech-detect", "-status-code", "-o", httpxOutput)

-l, -list string      input file containing list of hosts to process

launched with -l to take the previously generated .txt file as a list of domains
